name: CI - Timetable Generator V1

on:
  push:
    branches:
      - main
    paths:
      - 'timetable-generator-v1/**'
      - '.github/workflows/ci-timetable-generator-v1.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'timetable-generator-v1/**'
      - '.github/workflows/ci-timetable-generator-v1.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
